apiVersion: v1
kind: ReplicationController
metadata: 
  name: my-ReplicationController
  labels:
    app: my-rc-app
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: my-rc-app
    spec: 
      containers:
        -  name: my-containers
           image: nginx:latest
           ports:
             - containerPort: 80
  replicas: 3
  selector:
    app: my-rc-app               